### ISSUE TITLE
Return extensibility / schedules templating design

### ISSUE THREAD

**Issue by zakpatterson** [thegrims/UsTaxes#15]
We should come up with an easy way for users to add additional schedules they may need in their returns. As of now, the 1040 is the only one available.

* Data should be available to be filled and reusable from user's data model
* User's data model should be extensible so new data required for a schedule or form can be added.
* New schedule needs a link to download the appropriate PDF
* Needs to be easy to define a new template for generating the filled PDF from the user's data model

**Comment by thegrims** [comment]
To the data model points, as of right now form data is stored in redux in the structure of root->page->submittedFormText. This should be fairly extendable. The main barrier I can think of is that when the pdf is filled the object structure is flattened using `Object.assign({}, ...Object.values(state.information))` This means that all of the keys have to be unique. Not a problem right now, but it will be when more forms need to be filled

the PDF forms are loaded from github pages served from the PDFcdn branch. I tried loading directly from the IRS website but had issues with cross-origin requests.

**Comment by thegrims** [comment]
> Needs to be easy to define a new template for generating the filled PDF from the user's data model

This could be an awesome way to crowdsource the flatFieldMappings

**Comment by zakpatterson** [comment]
I think the new design of the forms and the redux state / data model address this. Downloading the PDF directly probably isn't possible in client side web mode. Desktop mode of course it would work.
