### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by zakpatterson** [thegrims/UsTaxes#16]
There are numerous reasons typescript is appropriate for this project. Just in terms of data validation, ensuring that the right type of data is used for form fields, constraining types of data, matching user's data model to pdf templates, etc.

Just a proposal that new code can come in TS form, and in the future existing typeless JS can go away.

**Comment by thegrims** [comment]
This is something I was thinking about as well, do you know if anything need to be changed in order to support typescript usage?

**Comment by zakpatterson** [comment]
I think there are a few settings to add, I'll just add it to build js and ts together in my next PR. Just wanted to make sure you were on board.
