### ISSUE TITLE
Change dropdown format to allow for easy navigation while being performant with many elements

### ISSUE THREAD

**Issue by thegrims** [thegrims/UsTaxes#17]
> The state dropdown is... confusing. Under the hood it's a bunch of <option>s like I'd expect, but they're popped out into some div, I guess so you can style them? Except this doesn't replicate the functionality of the basic HTML controls -- there's zero keyboard navigation. (To add insult to injury, you record the state as the two-letter thing I want to type anyway, but typing that after I open the dropdown does nothing.) It's not like React can't do a normal dropdown, so what went wrong here?

[https://www.reddit.com/r/opensource/comments/kqr89x/open_source_tax_filing_website/gi6d0jv/](https://www.reddit.com/r/opensource/comments/kqr89x/open_source_tax_filing_website/gi6d0jv/)

**Comment by zakpatterson** [comment]
I was also having problems getting that drop down rendered in tauri mode correctly. I'll try to rethink this.
