### ISSUE TITLE
add precommit hook to fix linting errors when commiting

### ISSUE THREAD

**Issue by thegrims** [thegrims/UsTaxes#42]
lint-staged and pretty-quick both look like really good options

https://prettier.io/docs/en/precommit.html

**Comment by zakpatterson** [comment]
Can you just add a check for this in netlify? `yarn run lint` will return with an exit status code of 1 if there were any errors, 0 if there were no errors.

**Comment by thegrims** [comment]
The idea is to add the hook not to detect errors but to have them be automatically & proactively fixed so a contributor can develop without worrying about formatting and then when committing, files are auto formatted to the projects formatting style

**Comment by zakpatterson** [comment]
All hooks can be bypassed though so it's still needed in CI anyway imo.

**Comment by thegrims** [comment]
@zakpatterson Changed the netlify build command to `CI=false npm run lint && npm run build`

**Comment by thegrims** [comment]
`CI=false` makes warnings not fail the build
