### ISSUE TITLE
Why are you using tauri/rust?

### ISSUE THREAD

**Issue by varunarora** [thegrims/UsTaxes#98]
I went through your tauri/rust code and it doesn't seem like much is going on. Why are you using it? I am trying to understand the rationale.

If there is way to just use a node-based webserver, it would reduce this unnecessary dependency.

**Comment by thegrims** [comment]
@varunarora Tauri & rust are being used for those that want to compile the site as a standalone desktop application using `npm run desktop-release` In the web app they are not used

**Comment by varunarora** [comment]
Got it, and got it! I just re-read the readme, and wow I messed up with this issue. Super clear. Thanks!

**Comment by thegrims** [comment]
No worries :)

**Comment by zakpatterson** [comment]
Hi @varunarora, It's still a work in progress, as Tauri is undergoing some major changes right now. I think the timing is good, and it will allow us to release extremely small binaries compared to making this an electron app. We also have a discord server now, come on over and hang out.
